import { Header } from "components/Header";
import styles from "styles/About.module.css";
import { Footer } from "components/Footer";
import Head from "next/head";
import { Top } from "components/Top";

export default function About() {
  const phrase = "Less Waste Less Price";

  return (
    <>
      <Head>
        <title>About</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <Top title={phrase} />
      <Footer />
    </>
  );
}
