import { Header } from "components/Header";
import styles from "@/styles/Home.module.css";
import { Footer } from "components/Footer";
import Head from "next/head";
import { Top } from "components/Top";
import { Topic } from "components/Topic";

export default function Home() {
  const multilineText =
    "すべての人に無駄なく\nより安く、より良い\n商品を届ける";

  return (
    <>
      <Head>
        <title>Ricebox</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <Top title={multilineText} />
      <Topic />
      <Footer />
    </>
  );
}
